export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN/REQUEST';
export const LOGIN_RESPONSE = 'LOGIN/RESPONSE';

export const REGISTER = 'REGISTER';
export const REGISTER_REQUEST = 'REGISTER/REQUEST';
export const REGISTER_RESPONSE = 'REGISTER/RESPONSE';

export const CHECK_TOKEN = 'CHECK_TOKEN';
export const CHECK_TOKEN_REQUEST = 'CHECK_TOKEN/REQUEST';
export const CHECK_TOKEN_RESPONSE = 'CHECK_TOKEN/RESPONSE';
export const CHECK_TOKEN_ERROR = 'CHECK_TOKEN/ERROR';

export const UNAUTHORIZED = 'UNAUTHORIZED';
