export const FETCH_SYSTEM_STATUS = 'FETCH_SYSTEM_STATUS';
export const FETCH_SYSTEM_STATUS_RESPONSE = `${FETCH_SYSTEM_STATUS}/RESPONSE`;
export const FETCH_SYSTEM_STATUS_ERROR = `${FETCH_SYSTEM_STATUS}/ERROR`;