import { ERROR, RESPONSE, REQUEST } from '../utils';

export const FETCH_SYSTEM_STATUS = 'FETCH_SYSTEM_STATUS';
export const FETCH_SYSTEM_STATUS_REQUEST = `${FETCH_SYSTEM_STATUS}/${REQUEST}`;
export const FETCH_SYSTEM_STATUS_RESPONSE = `${FETCH_SYSTEM_STATUS}/${RESPONSE}`;
export const FETCH_SYSTEM_STATUS_ERROR = `${FETCH_SYSTEM_STATUS}/${ERROR}`;