version: "3"
services:
  api:
    container_name: rad_api
    restart: always
    build: ./backend
    env_file:
      - ./backend/.env
    networks:
      - rad-net
    ports:
      - "8080:8080"
    environment:
      - RADIO_API_KEY=${RADIO_API_KEY}
  
  frontend:
    container_name: rad_frontend
    restart: always
    build: ./frontend
    networks:
      - rad-net
    ports:
      - "80:80"

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    networks:
      - rad-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  rad-net: