name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_backend:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12 ]
      fail-fast: true
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
          node-version: ${{ matrix.node }}

    - name: install
      run: npm install

    - name: lint
      run: npm run lint

  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node: [ 12 ]
      fail-fast: true

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
          node-version: ${{ matrix.node }}

    - name: install
      run: npm install

    - name: lint
      run: npm run lint

    - name: test
      run: npm test

    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./frontend/coverage/lcov.info

    - name: compile
      run: npm run prod